### ISSUE TITLE
Logitech Slim folio pro broken

### ISSUE THREAD

**Issue by varecham** [litchie/dospad#113]
After last update to v2.6 there is keyboard mapping broken, eg. backspace, numerical and special keys doesn`t respect selected keyboard layout.

Everything was OK in v2.5.

Is there any way how to downgrade to v2.5, please? Tank you.

**Comment by litchie** [comment]
No way to downgrade. 

Will fix backspace. numerical keys seems to work fine. Can you share a photo of your keyboard and show me which keys are not doing their job?

**Comment by varecham** [comment]
I found out, that it’s not about the malfunctioning keys (except the backspace), but the keyboard layout:
I am using Czech QWERTZ layout as a system default and it worked like a charm in v2.5. Since v2.6 the keyboard layout is forced as EN QWERTY and the IDOS doesn’t respect the default system settings.

Thank you!

**Comment by litchie** [comment]
Thank you for your following up, it's very helpful. 

The new keyboard support uses GCMouse API, so now you can use keyboard for game control purpose, and that is the reason your layout in settings are not respected.

Do you think I should add an option in settings to toggle this behavior? Of course, I prefer not to add any more settings if possible.

**Comment by varecham** [comment]
Since I know it’s a qwerty layout and not only malfunctional keys, it’s ok.

I don’t know the previous and current implementation differences, but I was able to control the game with my hw keyboard even before v2.5. I will try to use it more so I could tell you if there is anything missing, but for now the switch in the settings is not necessary.

Thank you!

**Comment by kentaromiura** [comment]
> No way to downgrade.
> 
> Will fix backspace. numerical keys seems to work fine. Can you share a photo of your keyboard and show me which keys are not doing their job?

As I have the same keyboard, Looks like the delete key, which used to be mapped correctly to backspace is now mapped to delete/canc, there seems to be no combinations to make it backspace, 
I had a case where the number row seems to be permantly mapped to function keys, not sure if I did something to make that happen while testing as usually should do that with cmd + , cannot reproduce.
Other than that all keys seems correct. 
Since I'm here Is there any way to map cmd + arrows to page up/ down, and maybe start and end? that would be very useful for editing code.

**Comment by litchie** [comment]
@kentaromiura Cmd + number keys are mapped to function keys. This is a work around for apple smart keyboards which got no function keys at all.

**Comment by kentaromiura** [comment]
Yeah, I get that, while testing I got on one occasion in a state where no matter what I did numbers where mapped to function keys *w/out* pressing cmd, now since I couldn't reproduce it, it might be that the actual cmd key was stuck, so nevermind it.
Another issue I notice is that now when I tab out of dosbox and back in the keyboard is not recognized anymore, not even if I detach and reattach it, before it used to work just fine.

**Comment by litchie** [comment]
@kentaromiura Will look into that

**Comment by varecham** [comment]
Since the update fixed the delete key, I am closing this issue. Thank you @litchie!
