### ISSUE TITLE
Idos 2 ver 1.1+ will crash apon launch.

### ISSUE THREAD

**Issue by IsThatLogic** [litchie/dospad#68]
All versions of idos 2 other than current 1.4 will crash apon launch. Is this due to incompatibility with the iPhone 6s+ or..? I’m stumped. I think versions such as 1.2 work with iOS 11 but when I launch the app it loads then crashes when dosbox loads. I did use the tweak appadmin to install the versions.

**Comment by litchie** [comment]
You should use the latest version.  Actually, even the version in AppStore is not updated anymore because Apple has changed its policy to the worse direction, and we effectively can't submit any update even if we turn off file sharing.

Please build from the Source or join the beta.

https://litchie.com/dospad
