### ISSUE TITLE
Magic Keyboard on iPad

### ISSUE THREAD

**Issue by ecstaticax** [litchie/dospad#85]
Hi, is there any possibility that Magic Keyboard (or external mouse support) will be supported in the next updates?
Regards.

**Comment by WeedyWeedSmoker** [comment]
@litchie That would be great!

That would mean external mouse support too thanks to a Bluetooth mouse or via a cable with iOS USB Camera Adapter…

Mini vMac already have this and it's really great! Here is the commit that made it work there : https://github.com/zydeco/minivmac4ios/pull/35

Thanks

**Comment by litchie** [comment]
@WeedyWeedSmoker Thanks for the link. That sounds promising!

**Comment by moromarino** [comment]
Please litchie, also don't forget the Smart Keyboard Folio! :)

**Comment by gilnoh** [comment]
I've submitted a pull request for bluetooth mouse right click support (#88), which is simpler, and actually ready to be merged.

I am closing the above mentioned older pull request #87, mainly due to the scale issue. If the scale issue (mouse coordinate - game coordinate differs) can be resolved, the mouse tracking of #87 is actually smoother. But currently scale issue cannot be resolved easily. 

I will try to revisit this in conjunction with direct touch mode. Hopefully I would be able to suggest another discussion / pull request in the coming weekend...

**Comment by litchie** [comment]
@gilnoh Thank you very much for the great work! #88 looks good enough, I will merge after I test it later.

**Comment by litchie** [comment]
Closing because the original issue should have been fixed.
